title: Streamdata Gallery eMuseum API docs
url: emuseum-api-docs.streamdata.gallery
tag: eMuseum API docs
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: emuseum-api-docs
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
